
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ogarcia/archlinux-x64"

  #config.vm.box_version = "= 2017.06.01"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = true

  config.vm.network "forwarded_port", guest: 5901, host: 7901, host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "2048"

    # Name of the machine displayed in Virtualbox
    vb.name = "os-dev"
  end

  config.vm.provision "install", type: "shell", path: "install-all.sh", privileged: false
  config.vm.provision "config", type: "shell", path: "setup-env.sh", privileged: false, run: "always"
end
